name: gene_dependency_representations
channels:
- conda-forge
dependencies:
- conda-forge::_libgcc_mutex	=	0.1
- conda-forge::_openmp_mutex	=	4.5
- conda-forge::anyio	=	3.6.1
- conda-forge::argon2-cffi	=	21.3.0
- conda-forge::argon2-cffi-bindings	=	21.2.0
- conda-forge::asttokens	=	2.0.5
- conda-forge::attrs	=	21.4.0
- conda-forge::babel	=	2.10.1
- conda-forge::backcall	=	0.2.0
- conda-forge::backports	=	1.0
- conda-forge::backports.functools_lru_cache	=	1.6.4
- conda-forge::beautifulsoup4	=	4.11.1
- conda-forge::bleach	=	5.0.0
- conda-forge::brotlipy	=	0.7.0
- conda-forge::bzip2	=	1.0.8
- conda-forge::ca-certificates	=	2022.5.18.1
- conda-forge::certifi	=	2022.5.18.1
- conda-forge::cffi	=	1.15.0
- conda-forge::charset-normalizer	=	2.0.12
- conda-forge::cryptography	=	37.0.2
- conda-forge::debugpy	=	1.6.0
- conda-forge::decorator	=	5.1.1
- conda-forge::defusedxml	=	0.7.1
- conda-forge::entrypoints	=	0.4
- conda-forge::executing	=	0.8.3
- conda-forge::flit-core	=	3.7.1
- conda-forge::idna	=	3.3
- conda-forge::importlib-metadata	=	4.11.4
- conda-forge::importlib_metadata	=	4.11.4
- conda-forge::importlib_resources	=	5.7.1
- conda-forge::ipykernel	=	6.13.1
- conda-forge::ipython	=	8.4.0
- conda-forge::ipython_genutils	=	0.2.0
- conda-forge::jedi	=	0.18.1
- conda-forge::jinja2	=	3.1.2
- conda-forge::json5	=	0.9.5
- conda-forge::jsonschema	=	4.6.0
- conda-forge::jupyter_client	=	7.3.4
- conda-forge::jupyter_core	=	4.10.0
- conda-forge::jupyter_server	=	1.17.1
- conda-forge::jupyterlab	=	3.4.3
- conda-forge::jupyterlab_pygments	=	0.2.2
- conda-forge::jupyterlab_server	=	2.14.0
- conda-forge::ld_impl_linux-64	=	2.36.1
- conda-forge::libffi	=	3.4.2
- conda-forge::libgcc-ng	=	12.1.0
- conda-forge::libgomp	=	12.1.0
- conda-forge::libnsl	=	2.0.0
- conda-forge::libsodium	=	1.0.18
- conda-forge::libstdcxx-ng	=	12.1.0
- conda-forge::libuuid	=	2.32.1
- conda-forge::libzlib	=	1.2.12
- conda-forge::markupsafe	=	2.1.1
- conda-forge::matplotlib-inline	=	0.1.3
- conda-forge::mistune	=	0.8.4
- conda-forge::nb_conda_kernels	=	2.3.1
- conda-forge::nbclassic	=	0.3.7
- conda-forge::nbclient	=	0.6.4
- conda-forge::nbconvert	=	6.5.0
- conda-forge::nbconvert-core	=	6.5.0
- conda-forge::nbconvert-pandoc	=	6.5.0
- conda-forge::nbformat	=	5.4.0
- conda-forge::ncurses	=	6.3
- conda-forge::nest-asyncio	=	1.5.5
- conda-forge::notebook	=	6.4.12
- conda-forge::notebook-shim	=	0.1.0
- conda-forge::openssl	=	1.1.1o
- conda-forge::packaging	=	21.3
- conda-forge::pandoc	=	2.18
- conda-forge::pandocfilters	=	1.5.0
- conda-forge::parso	=	0.8.3
- conda-forge::pexpect	=	4.8.0
- conda-forge::pickleshare	=	0.7.5
- conda-forge::pip	=	22.1.2
- conda-forge::prometheus_client	=	0.14.1
- conda-forge::prompt-toolkit	=	3.0.29
- conda-forge::psutil	=	5.9.1
- conda-forge::ptyprocess	=	0.7.0
- conda-forge::pure_eval	=	0.2.2
- conda-forge::pycparser	=	2.21
- conda-forge::pygments	=	2.12.0
- conda-forge::pyopenssl	=	22.0.0
- conda-forge::pyparsing	=	3.0.9
- conda-forge::pyrsistent	=	0.18.1
- conda-forge::pysocks	=	1.7.1
- conda-forge::python	=	3.9.13
- conda-forge::python-dateutil	=	2.8.2
- conda-forge::python-fastjsonschema	=	2.15.3
- conda-forge::python_abi	=	3.9
- conda-forge::pytz	=	2022.1
- conda-forge::pyzmq	=	23.1.0
- conda-forge::readline	=	8.1.2
- conda-forge::requests	=	2.28.0
- conda-forge::send2trash	=	1.8.0
- conda-forge::setuptools	=	62.3.4
- conda-forge::six	=	1.16.0
- conda-forge::sniffio	=	1.2.0
- conda-forge::soupsieve	=	2.3.1
- conda-forge::sqlite	=	3.38.5
- conda-forge::stack_data	=	0.2.0
- conda-forge::terminado	=	0.15.0
- conda-forge::tinycss2	=	1.1.1
- conda-forge::tk	=	8.6.12
- conda-forge::tornado	=	6.1
- conda-forge::traitlets	=	5.2.2.post1
- conda-forge::tzdata	=	2022a
- conda-forge::urllib3	=	1.26.9
- conda-forge::wcwidth	=	0.2.5
- conda-forge::webencodings	=	0.5.1
- conda-forge::websocket-client	=	1.3.2
- conda-forge::wheel	=	0.37.1
- conda-forge::xz	=	5.2.5
- conda-forge::zeromq	=	4.3.4
- conda-forge::zipp	=	3.8.0
- conda-forge::zlib	=	1.2.12
